interview_db/urls.py
# copyright 2026 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

from django.conf import settings
from django.contrib import admin
from django.urls import re_path, path
from django.views.generic import TemplateView
from interview_db.views import *

app_name = "interview_db"

# start with an empty url array
urlpatterns = []

# add debug routes for developing error pages
if settings.DEBUG:
    urlpatterns += [
        re_path(
            r"^500$",
            TemplateView.as_view(template_name="500.html"),
            name="500_response",
        ),
        re_path(
            r"^404$",
            TemplateView.as_view(template_name="404.html"),
            name="404_response",
        ),
        re_path(
            r"^403$",
            TemplateView.as_view(template_name="403.html"),
            name="403_response",
        ),
    ]


urlpatterns += [
    re_path(r'^admin', admin.site.urls),
    path('students', DefaultPageView.as_view(), name="students"),
    path('collections', DefaultPageView.as_view(), name="collections"),
    path('about', DefaultPageView.as_view(), name="about"),
    path('api/students/', InterviewListView.as_view(),
         name="student-list"),
    path('api/students/<int:id>/', SingleInterviewView.as_view(),
         name="student-detail"),
    path('api/students/<int:id>/image/', ImageView.as_view(),
         name="student-image"),
    path('api/students/<int:id>/topics/', InterviewTopicsView.as_view(),
         name="interview-topics"),
    path('api/collections/', CollectionListView.as_view(),
         name="collection-list"),
    path('api/collections/<int:id>/info/',
         CollectionInfoView.as_view(),
         name="collection-info",),
    path('api/collections/<int:id>/',
         CollectionStoryView.as_view(),
         name="collection-stories",),
    path('api/majors/', MajorListView.as_view(), name="major-list"),
    path('api/random/', RandomStudentsView.as_view(), name="random-students"),
    path('api/students/count/', InterviewCountView.as_view(),
         name="interview-count"),
    path('api/stories/count/', StoryCountView.as_view(), name="story-count"),
    re_path(r"^.*$", DefaultPageView.as_view(), name="home"),
]

interview_db/models.py
# copyright 2026 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

from django.db import models
from django.template.defaultfilters import truncatechars
from django.urls import reverse


class StudentType(models.Model):
    TYPE = (
        ('Commuter', 'Commuter'),
        ('Exchange', 'Exchange'),
        ('First-Gen', 'First-Gen'),
        ('International', 'International'),
        ('LGBTQ', 'LGBTQ'),
        ('Transfer', 'Transfer'),
    )

    type = models.CharField(choices=TYPE,
                            max_length=100,
                            blank=True,
                            null=True
                            )

    def __str__(self):
        return self.type


class Major(models.Model):

    full_title = models.CharField(max_length=255)
    major_abbreviation = models.CharField(max_length=10)

    def __str__(self):
        return self.major_abbreviation

    class Meta:
        ordering = ['major_abbreviation', ]


class Location(models.Model):

    location = models.CharField(max_length=255,
                                )

    def __str__(self):
        return self.location

    class Meta:
        ordering = ['location', ]


class Student(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255, blank=True, null=True)
    uw_netid = models.CharField(max_length=10, blank=True, null=True)
    email = models.EmailField(max_length=255,
                              blank=True,
                              null=True)
    artifacts_url = models.URLField(
        help_text="URL for Google Drive folder where student "
                  "artifacts are stored.")
    follow_up_consent = models.BooleanField()

    def __str__(self):
        return str(self.first_name) + " " + str(self.last_name)

    class Meta:
        ordering = ['first_name', ]


class Interview(models.Model):
    YEAR_LEFT = (
        ('< 1', '< 1'),
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6')
    )
    YEAR = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
        ('6', '6'),
        ('7', '7'),
        ('8', '8')
    )
    STANDING = (
        ('Fr', 'Freshman'),
        ('So', 'Sophomore'),
        ('Jr', 'Junior'),
        ('Sr', 'Senior'),
        ('Al', 'Alumni - undergrad'),
        ('Ma', 'Masters'),
        ('Ph', 'PhD')
    )
    QUARTER = (
        ('au', 'Autumn'),
        ('wi', 'Winter'),
        ('sp', 'Spring'),
        ('su', 'Summer')
    )

    student = models.ForeignKey(Student, on_delete=models.PROTECT)
    date = models.DateField()
    interview_quarter = models.CharField(choices=QUARTER, max_length=2)
    interview_location = models.ManyToManyField(Location,
                                                blank=True)
    signed_release_form = models.BooleanField()
    pull_quote = models.TextField(
        max_length=200,
        help_text="A brief, 200 character or less, quote "
                  "from interview that will engage people.")
    interview_notes_url = models.URLField(
        blank=True,
        null=True,
        help_text="Direct URL for transcribed interview, "
                  "edited for publication.")
    image = models.ImageField(
        upload_to='interview_db_images',
        default="",
        blank=True,
        null=True,
        help_text="Image should be 1875 x 2882 (any orientation), "
                  "saved as an optimized High Quality (60) JPEG.")
    image_is_not_identifying = models.BooleanField(
        help_text="This image doesn't include the student's face.")
    image_alt_text = models.CharField(
        max_length=255, blank=True, null=True,
        help_text="Describe the image in detail so that a non-sighted "
                  "user might also get that personal connection.")
    intended_major = models.BooleanField(blank=True)
    major = models.ManyToManyField(Major)
    standing = models.CharField(choices=STANDING,
                                max_length=2,
                                blank=True)
    years_until_graduation = models.CharField(choices=YEAR_LEFT,
                                              max_length=3,
                                              blank=True)
    current_year = models.CharField(choices=YEAR,
                                    max_length=1,
                                    blank=True)
    student_type = models.ManyToManyField(StudentType,
                                          blank=True)
    no_identifying_photo = models.BooleanField(
        help_text="No photo of face can be published.")
    no_real_name = models.BooleanField(help_text="Cannot publish real name.")
    no_publishing_stories = models.BooleanField(
        help_text="Stories and artifacts can only be "
                  "used internally for research.")
    other_publishing_restrictions = models.BooleanField(
        help_text="They had other restrictions on the use of their data.")
    other_publishing_restrictions_notes = models.TextField(
        blank=True, null=True)

    def __str__(self):
        return str(self.student) + ": " + str(self.date)

    class Meta:
        ordering = ['student', '-date']

    def declared_major(self):
        return ', '.join(
            [major.full_title for major in self.major.all()]
        )

    def get_absolute_url(self):
        return reverse('interview_db:interview', args=(),
                       kwargs={'interview_id': str(self.id)})


class ResourceCategory(models.Model):
    resource_category = models.CharField(max_length=500)
    definition = models.CharField(max_length=5000)

    def __str__(self):
        return self.resource_category

    class Meta:
        ordering = ['resource_category']


class ResourceLink(models.Model):
    url = models.URLField()
    title = models.CharField(
        max_length=255,
        help_text="The text used as the link to the resource.")
    description = models.CharField(
        max_length=5000,
        help_text="Provide a <strong>brief</strong> description. "
                  "Something that could be the title attribute of the link.")
    category = models.ForeignKey(
        ResourceCategory,
        on_delete=models.PROTECT,
        help_text=(
            'See our <a href="https://docs.google.com/document/d/'
            '1nDEYzdfqIDRQwOEKhRHZiiX8hHj4OxiTlNbYmF4dZUQ/edit?usp=sharing">'
            'category guidelines</a> for resource links.')
        )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']


class SubCode(models.Model):
    subcode = models.CharField(max_length=255)
    definition = models.CharField(max_length=5000)

    class Meta:
        ordering = ['subcode']

    def __str__(self):
        return self.subcode


class Code(models.Model):
    topic = models.CharField(max_length=20)
    code = models.CharField(max_length=255)
    definition = models.TextField(max_length=5000)

    class Meta:
        ordering = ['topic', 'code']

    def __str__(self):
        return str(self.topic) + " - " + str(self.code)

    def get_absolute_url(self):
        return reverse('interview_db:code', args=(),
                       kwargs={'code_id': str(self.id)})


class Story(models.Model):
    interview = models.ForeignKey(Interview, on_delete=models.PROTECT)
    story = models.TextField(help_text="Stories should be understandable and "
                                       "interesting all on their own.")
    related_resource_links = models.ManyToManyField(
        ResourceLink,
        blank=True,
        help_text="Select any resources that would be useful "
                  "or relevant in this situation, "
                  "whether mentioned in the story or not.<br/>"
    )
    story_order_position = models.IntegerField(
        help_text="Logical position of story within context of other stories "
                  "w/in interview. <strong>Must be unique</strong> "
                  "to other stories of the same interview!")
    code = models.ManyToManyField(Code, through='Coding',
                                  through_fields=('story', 'code'))
    subcode = models.ManyToManyField(SubCode, through='Coding',
                                     through_fields=('story', 'subcode'))

    def __str__(self):
        return str(self.interview) + ": " + str(self.story_order_position)

    @property
    def short_story(self):
        return truncatechars(self.story, 150)

    class Meta:
        verbose_name_plural = "Stories"
        unique_together = ('interview', 'story_order_position')
        ordering = ['story_order_position']


class Coding(models.Model):
    code = models.ForeignKey(
        Code,
        on_delete=models.PROTECT,
        help_text=(
            'See our <a href="https://docs.google.com/document/d/'
            '18el41a2DJ4hdHk-yPVQEDBSzGNb0HO-mlGHp33-nCqE/edit?usp=sharing">'
            'code definitions</a>.')
    )
    subcode = models.ForeignKey(SubCode, on_delete=models.PROTECT)

    story = models.ForeignKey(Story, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.code) + " > " + str(self.subcode)

    class Meta:
        ordering = ['code']


class Collection(models.Model):
    TOPIC = (
        ('Getting Help', 'Getting Help'),
        ('Advice', 'Advice'),
        ('Mental Wellness', 'Mental Wellness'),
        ('Coming to College', 'Coming to College'),
        ('Majors', 'Majors'),
        ('Finding Community', 'Finding Community'),
        ('Self Reflection', 'Self Reflection'),
        ('Applying to Majors', 'Applying to Majors'),
        ('Balancing/Adulting', 'Balancing/Adulting'),
        ('Getting a Job', 'Getting a Job'),
        ('Graduation', 'Graduation'),
    )

    topic = models.CharField(choices=TOPIC,
                             max_length=100,
                             blank=True,

interview_db/templates/index.html
<!-- TO-DO: delete -->

{% extends 'base.html' %}

{% block content %}
    {% if interview_list %}
    <ul>
    {% for interview in interview_list %}
    {% if interview.story_set.all %}
    <li>
    <a href="{{ interview.get_absolute_url }}" class="idb-list-container people-container" title="Read {{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}'s full interview: {{ interview.date }}" >
    {% if interview.image %}<img src="{{ interview.image.url }}">{% else %}<img src="../media/interview_db_images/no-image.jpg">{% endif %}
    <div class="person-container"><h2>{{ interview.pull_quote }}</h2>
   <p>{{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}. <br/>
   <em>{{ interview.get_standing_display }}, {{ interview.major.all|join:", " }}{% if interview.student_type.all %}, {{ interview.student_type.all|join:", " }}{% endif %}</em></p>    
    </div>
     </a>
   </li>
   {% endif %}
    {% endfor %} 
    {% else %}
        <p>
            There are no students available.
        </p>
    </ul>
    {% endif %}

{% endblock %}

interview_db/templates/interview.html
{% extends 'base.html' %}

{% block header %}
Interview
{% endblock %}

{% block content %}
    {% if interview.story_set.all %}
    <div class="idb-list-container" >
    {% if interview.image %}<img src="{{ interview.image.url }}">{% else %}<img src="../media/interview_db_images/no-image.jpg">{% endif %}
    <div><h2>{{ interview.student.first_name }} {{ interview.student.last_name|first }}. </h2>
    <h3 class="idb-header">{{ interview.date }}</h3>
    <span><em>stories: {{interview.story_set.count}}</em></span>
    </div>
        <ul >
            {% for story in interview.story_set.all %}
            <li class="idb-story-container">
                {{story.story}}
                <p>{% for each in story.coding_set.all %}<em>
                <a href="{{ each.code.get_absolute_url }}" title="All stories tagged: {{ each.code }}">{{ each.code }}, <strong>{{ each.subcode}}</strong></a></em><br/>
                {% endfor %}  </p>                
            </li>
            {% endfor %} 
        </ul>
    </div>
    {% else %}
        <p>
            There are no student stories available.
        </p>
    {% endif %}

{% endblock %}

interview_db/templates/interviews.html
{% extends 'base.html' %}

{% block content %}
    {% if interview_list %}
    {% for interview in interview_list %}
    {% if interview.story_set.all %}
    <div class="idb-list-container" >
    {% if interview.image %}<img src="{{ interview.image.url }}">{% else %}<img src="../media/interview_db_images/no-image.jpg">{% endif %}
    <div><h2><a href="{{ interview.get_absolute_url }}" title="Read {{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}'s full interview: {{ interview.date }}" >{{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}.</a></h2>
    <h3 class="idb-header">{{ interview.date }}</h3>
    <span><em>stories: {{interview.story_set.count}}</em></span>
    </div>
        <ul >
            {% for story in interview.story_set.all %}
            <li class="idb-story-container">
                {{story.story}}
                <p>{% for each in story.coding_set.all %}<em>
                <a href="{{ each.code.get_absolute_url }}" title="All stories tagged: {{ each.code }}">{{ each.code }}, <strong>{{ each.subcode}}</strong></a></em><br/>
                {% endfor %} </p>                 
            </li>
            {% endfor %} 
        </ul>
    </div>
     {% endif %}
    {% endfor %} 
    {% else %}
        <p>
            There are no student stories available.
        </p>
    {% endif %}

{% endblock %}

interview_db/templates/people.html
{% extends 'base.html' %}

{% block content %}
    {% if interview_list %}
    <ul>
    {% for interview in interview_list %}
    {% if interview.story_set.all %}
    <li>
    <a href="{{ interview.get_absolute_url }}" class="idb-list-container people-container" title="Read {{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}'s full interview: {{ interview.date }}" >
    {% if interview.image %}<img src="{{ interview.image.url }}">{% else %}<img src="../media/interview_db_images/no-image.jpg">{% endif %}
    <div class="person-container"><h2>{{ interview.pull_quote }}</h2>
   <p>{{ interview.student.first_name }} {{ interview.student.last_name|make_list|first }}. <br/>
   <em>{{ interview.get_standing_display }}, {{ interview.major.all|join:", " }}{% if interview.student_type.all %}, {{ interview.student_type.all|join:", " }}{% endif %}</em></p>    
    </div>
     </a>
   </li>
   {% endif %}
    {% endfor %} 
    {% else %}
        <p>
            There are no students available.
        </p>
    </ul>
    {% endif %}

{% endblock %}

interview_db/templates/topic.html
{% extends 'base.html' %}

{% block header %}
Topic
{% endblock %}

{% block content %}

    {% if code.story_set.all %}
    <div class="idb-list-container"> 
        <h2 class="idb-header">{{code}}</h2> <span><em>stories: {{code.story_set.count}}</em></span>
                    {% for each in code.coding_set.all %}
                    {% if each.subcode %}
                    <div class="idb-story-container"><strong><a href="{{ each.story.interview.get_absolute_url }}" title="Read {{ each.story.interview.student.first_name }} {{ each.story.interview.student.last_name|make_list|first }}'s full interview: {{ each.story.interview.date }}" >{{each.story.interview.student.first_name}} {{each.story.interview.student.last_name|make_list|first}} : {{each.story.interview.date}}</a></strong>
                        <ul>
                            <li>{{each.story.story}}<br/><span class="idb-story-note"><em>{{each.subcode}}</em></span></li>    
                             
                        </ul> 
                    </div>
                    {% endif %}
                    {% endfor %}
                   
    </div>
    {% else %}
    <p>
    There are no student stories available.
    </p>
    {% endif %}

{% endblock %}

interview_db/templates/topics.html
{% extends 'base.html' %}

{% block content %}

    {% if code_list %}
        {% for code in code_list %}
            {% if code.story_set.all %}
            <div class="idb-list-container"> 
                <h2 class="idb-header"> <a href="{{ code.get_absolute_url }}">{{code}}</a></h2> <span><em>stories: {{code.story_set.count}}</em></span>              
            </div>
            {% endif %}
        {% endfor %} 
    {% else %}
        <p>
            There are no topics available.
        </p>
    {% endif %}

{% endblock %}

interview_db/templates/vue.html
{% load static %}
{% load vite %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../interview_db_vue/images/purplew.png">
  <!-- vite css bundle -->
  {% vite_styles 'interview_db_vue/main.js' %}
</head>

<body {% if google_analytics %}data-google-analytics="{{ google_analytics }}"{% endif %} {% if logout_url %}data-logout-url="{{ logout_url }}"{% endif %} data-django-debug="{{ django_debug|lower}}">
    {% csrf_token %}

    <!-- vue app will be injected here -->
    <div id="app"></div>

    <!-- vite js bundle -->
    {% vite_scripts 'interview_db_vue/main.js' %}

</body>
</html>